export const heroes = [
    {
        "id":1,
        "name":"Anti-Mage",
        "primary_attr":"agi",
        "attack_type":"Melee",
        "img": "https://user-images.githubusercontent.com/20388583/27767004-fa76a52a-5eb3-11e7-8765-5d8afd10ef53.png",
        "roles":[
            "Carry",
            "Escape",
            "Nuker"
        ],
        "bad_against": [
            "Axe",
            "Bane",
            "Bloodseeker",
            "Disruptor",
            "Doom",
            "Drow Ranger",
            "Legion Commander",
            "Meepo",
            "Night Stalker",
            "Outworld Devourer",
            "Phantom Assassin",
            "Slardar",
            "Shadow Demon",
            "Templar Assassin",
            "Tiny",
            "Troll Warlord"
        ],
        "good_against": [
            "Ancient Apparition",
            "Arc Warden",
            "Clockwerk",
            "Elder Titan",
            "Medusa",
            "Morphling",
            "Phoenix",
            "Pugna",
            "Spectre",
            "Storm Spirit",
            "Undying",
            "Venomancer",
            "Wraith King",
            "Zeus"
        ]
    },
    {
        "id":2,
        "name":"Axe",
        "primary_attr":"str",
        "attack_type":"Melee",
        "img": "https://user-images.githubusercontent.com/20388583/27767019-48f52866-5eb4-11e7-8cdd-65f8a85587ff.png",
        "roles":[
            "Initiator",
            "Durable",
            "Disabler",
            "Jungler"
        ],
        "bad_against": [
            "Doom",
            "Jakiro",
            "Lifestealer",
            "Necrophos",
            "Outworld Devourer",
            "Shadow Demon",
            "Spectre",
            "Timbersaw",
            "Ursa",
            "Viper"
        ],
        "good_against": [
            "Broodmother",
            "Chaos Knight",
            "Dazzle",
            "Huskar",
            "Legion Commander",
            "Natures Prophet",
            "Phantom Assassin",
            "Phantom Lancer",
            "Slark",
            "Terrorblade",
            "Troll Warlord",
            "Weaver"
        ]
    },
    {
        "id":3,
        "name":"Bane",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "img": "https://user-images.githubusercontent.com/20388583/27767016-41b90b76-5eb4-11e7-8363-2058d4262070.png",
        "roles":[
            "Support",
            "Disabler",
            "Nuker",
            "Durable"
        ],
        "bad_against": [
            "Phantom Lancer",
            "Slark",
            "Chaos Knight",
            "Razor",
            "Pudge"
        ],
        "good_against": [
            "Medusa",
            "Phantom Assassin",
            "Dazzle",
            "Dark Seer",
            "Faceless Void",
            "Bloodseeker"
        ]
    },
    {
        "id":4,
        "name":"Bloodseeker",
        "primary_attr":"agi",
        "attack_type":"Melee",
        "img": "https://user-images.githubusercontent.com/20388583/27767017-45e7b094-5eb4-11e7-8590-16111cab771e.png",
        "roles":[
            "Carry",
            "Disabler",
            "Jungler",
            "Nuker",
            "Initiator"
        ],
        "bad_against": [
            "Abaddon",
            "Dazzle",
            "Ember Spirit",
            "Faceless Void",
            "Medusa",
            "Morphling",
            "Omniknight",
            "Storm Spirit",
            "Techies",
            "Troll Warlord",
            "Underlord"
        ],
        "good_against": [
            "Anti-Mage",
            "Clinkz",
            "Huskar",
            "Meepo",
            "Riki",
            "Slark",
            "Sniper",
            "Timbersaw",
            "Weaver",
            "Windranger"
        ]
    },
    {
        "id":5,
        "name":"Crystal Maiden",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "img": "https://user-images.githubusercontent.com/20388583/27767015-3d93e4bc-5eb4-11e7-9cb7-0bddb925990d.png",
        "roles":[
            "Support",
            "Disabler",
            "Nuker",
            "Jungler"
        ],
        "bad_against": [
            "Ancient Apparition",
            "Bristleback",
            "Clockwerk",
            "Doom",
            "Earth Spirit",
            "Legion Commander",
            "Naga Siren",
            "Nyx Assassin",
            "Tidehunter",
            "Tusk",
            "Visage"
        ],
        "good_against": [
            "Slark",
            "Phantom Assassin",
            "Templar Assassin"
        ]
    },
    {
        "id":6,
        "name":"Drow Ranger",
        "primary_attr":"agi",
        "attack_type":"Ranged",
        "img": "https://user-images.githubusercontent.com/20388583/27767021-502ce376-5eb4-11e7-9678-f92e99c5f37f.png",
        "roles":[
            "Carry",
            "Disabler",
            "Pusher"
        ],
        "bad_against": [
            "Broodmother",
            "Clockwerk",
            "Huskar",
            "Lycan",
            "Riki",
            "Phantom Lancer"
        ],
        "good_against": [
            "Ember Spirit",
            "Juggernaut",
            "Anti-Mage",
            "Weaver"
        ]
    },
    {
        "id":7,
        "name":"Earthshaker",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Support",
            "Initiator",
            "Disabler",
            "Nuker"
        ],
        "bad_against": [
            "Clockwerk",
            "Disruptor",
            "Earth Spirit",
            "Lifestealer",
            "Phoenix",
            "Skywrath Mage",
            "Sniper",
            "Spectre",
            "Zeus"
        ],
        "good_against": [
            "Enigma",
            "Broodmother",
            "Chaos Knight",
            "Meepo",
            "Naga Siren",
            "Natures Prophet",
            "Phantom Lancer"
        ]
    },
    {
        "id":8,
        "name":"Juggernaut",
        "primary_attr":"agi",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Pusher",
            "Escape"
        ],
        "bad_against": [
            "Phantom Lancer",
            "Clinkz",
            "Axe",
            "Outworld Devourer",
            "Ursa"
        ],
        "good_against": [
            "Invoker",
            "Keeper of the Light",
            "Necrophos",
            "Phoenix",
            "Templar Assassin",
            "Zeus"
        ]
    },
    {
        "id":9,
        "name":"Mirana",
        "primary_attr":"agi",
        "attack_type":"Ranged",
        "roles":[
            "Carry",
            "Support",
            "Escape",
            "Nuker",
            "Disabler"
        ],
        "bad_against": [
            "Puck",
            "Abaddon",
            "Meepo",
            "Huskar",
            "Arc Warden",
            "Slark"
        ],
        "good_against": [
            "Drow Ranger",
            "Crystal Maiden",
            "Witch Doctor",
            "Techies"
        ]
    },
    {
        "id":10,
        "name":"Morphling",
        "primary_attr":"agi",
        "attack_type":"Ranged",
        "roles":[
            "Carry",
            "Escape",
            "Durable",
            "Nuker",
            "Disabler"
        ],
        "bad_against": [
            "Ancient Apparition",
            "Anti-Mage",
            "Arc Warden",
            "Earth Spirit",
            "Ember Spirit",
            "Elder Titan",
            "Lion",
            "Lifestealer",
            "Meepo",
            "Outworld Devourer",
            "Rubick",
            "Skywrath Mage"
        ],
        "good_against": [
            "Bloodseeker",
            "Drow Ranger",
            "Lone Druid",
            "Phantom Assassin",
            "Sniper"
        ]
    },
    {
        "id":11,
        "name":"Shadow Fiend",
        "primary_attr":"agi",
        "attack_type":"Ranged",
        "roles":[
            "Carry",
            "Nuker"
        ]
    },
    {
        "id":12,
        "name":"Phantom Lancer",
        "primary_attr":"agi",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Escape",
            "Pusher",
            "Nuker"
        ]
    },
    {
        "id":13,
        "name":"Puck",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Initiator",
            "Disabler",
            "Escape",
            "Nuker"
        ]
    },
    {
        "id":14,
        "name":"Pudge",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Disabler",
            "Initiator",
            "Durable",
            "Nuker"
        ]
    },
    {
        "id":15,
        "name":"Razor",
        "primary_attr":"agi",
        "attack_type":"Ranged",
        "roles":[
            "Carry",
            "Durable",
            "Nuker",
            "Pusher"
        ]
    },
    {
        "id":16,
        "name":"Sand King",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Initiator",
            "Disabler",
            "Nuker",
            "Escape",
            "Jungler"
        ]
    },
    {
        "id":17,
        "name":"Storm Spirit",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Carry",
            "Escape",
            "Nuker",
            "Initiator",
            "Disabler"
        ]
    },
    {
        "id":18,
        "name":"Sven",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Disabler",
            "Initiator",
            "Durable",
            "Nuker"
        ]
    },
    {
        "id":19,
        "name":"Tiny",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Nuker",
            "Pusher",
            "Initiator",
            "Durable",
            "Disabler"
        ]
    },
    {
        "id":20,
        "name":"Vengeful Spirit",
        "primary_attr":"agi",
        "attack_type":"Ranged",
        "roles":[
            "Support",
            "Initiator",
            "Disabler",
            "Nuker",
            "Escape"
        ]
    },
    {
        "id":21,
        "name":"Windranger",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Carry",
            "Support",
            "Disabler",
            "Escape",
            "Nuker"
        ]
    },
    {
        "id":22,
        "name":"Zeus",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Nuker"
        ]
    },
    {
        "id":23,
        "name":"Kunkka",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Disabler",
            "Initiator",
            "Durable",
            "Nuker"
        ]
    },
    {
        "id":25,
        "name":"Lina",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Support",
            "Carry",
            "Nuker",
            "Disabler"
        ]
    },
    {
        "id":26,
        "name":"Lion",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Support",
            "Disabler",
            "Nuker",
            "Initiator"
        ]
    },
    {
        "id":27,
        "name":"Shadow Shaman",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Support",
            "Pusher",
            "Disabler",
            "Nuker",
            "Initiator"
        ]
    },
    {
        "id":28,
        "name":"Slardar",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Durable",
            "Initiator",
            "Disabler",
            "Escape"
        ]
    },
    {
        "id":29,
        "name":"Tidehunter",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Initiator",
            "Durable",
            "Disabler",
            "Nuker"
        ]
    },
    {
        "id":30,
        "name":"Witch Doctor",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Support",
            "Nuker",
            "Disabler"
        ]
    },
    {
        "id":31,
        "name":"Lich",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Support",
            "Nuker"
        ]
    },
    {
        "id":32,
        "name":"Riki",
        "primary_attr":"agi",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Escape",
            "Disabler"
        ]
    },
    {
        "id":33,
        "name":"Enigma",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Disabler",
            "Jungler",
            "Initiator",
            "Pusher"
        ]
    },
    {
        "id":34,
        "name":"Tinker",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Carry",
            "Nuker",
            "Pusher"
        ]
    },
    {
        "id":35,
        "name":"Sniper",
        "primary_attr":"agi",
        "attack_type":"Ranged",
        "roles":[
            "Carry",
            "Nuker"
        ]
    },
    {
        "id":36,
        "name":"Necrophos",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Carry",
            "Nuker",
            "Durable",
            "Disabler"
        ]
    },
    {
        "id":37,
        "name":"Warlock",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Support",
            "Initiator",
            "Disabler"
        ]
    },
    {
        "id":38,
        "name":"Beastmaster",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Initiator",
            "Disabler",
            "Durable",
            "Nuker"
        ]
    },
    {
        "id":39,
        "name":"Queen of Pain",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Carry",
            "Nuker",
            "Escape"
        ]
    },
    {
        "id":40,
        "name":"Venomancer",
        "primary_attr":"agi",
        "attack_type":"Ranged",
        "roles":[
            "Support",
            "Nuker",
            "Initiator",
            "Pusher",
            "Disabler"
        ]
    },
    {
        "id":41,
        "name":"Faceless Void",
        "primary_attr":"agi",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Initiator",
            "Disabler",
            "Escape",
            "Durable"
        ]
    },
    {
        "id":42,
        "name":"Wraith King",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Support",
            "Durable",
            "Disabler",
            "Initiator"
        ]
    },
    {
        "id":43,
        "name":"Death Prophet",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Carry",
            "Pusher",
            "Nuker",
            "Disabler"
        ]
    },
    {
        "id":44,
        "name":"Phantom Assassin",
        "primary_attr":"agi",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Escape"
        ]
    },
    {
        "id":45,
        "name":"Pugna",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Nuker",
            "Pusher"
        ]
    },
    {
        "id":46,
        "name":"Templar Assassin",
        "primary_attr":"agi",
        "attack_type":"Ranged",
        "roles":[
            "Carry",
            "Escape"
        ]
    },
    {
        "id":47,
        "name":"Viper",
        "primary_attr":"agi",
        "attack_type":"Ranged",
        "roles":[
            "Carry",
            "Durable",
            "Initiator",
            "Disabler"
        ]
    },
    {
        "id":48,
        "name":"Luna",
        "primary_attr":"agi",
        "attack_type":"Ranged",
        "roles":[
            "Carry",
            "Nuker",
            "Pusher"
        ]
    },
    {
        "id":49,
        "name":"Dragon Knight",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Pusher",
            "Durable",
            "Disabler",
            "Initiator",
            "Nuker"
        ]
    },
    {
        "id":50,
        "name":"Dazzle",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Support",
            "Nuker",
            "Disabler"
        ]
    },
    {
        "id":51,
        "name":"Clockwerk",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Initiator",
            "Disabler",
            "Durable",
            "Nuker"
        ]
    },
    {
        "id":52,
        "name":"Leshrac",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Carry",
            "Support",
            "Nuker",
            "Pusher",
            "Disabler"
        ]
    },
    {
        "id":53,
        "name":"Nature's Prophet",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Carry",
            "Jungler",
            "Pusher",
            "Escape",
            "Nuker"
        ]
    },
    {
        "id":54,
        "name":"Lifestealer",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Durable",
            "Jungler",
            "Escape",
            "Disabler"
        ]
    },
    {
        "id":55,
        "name":"Dark Seer",
        "primary_attr":"int",
        "attack_type":"Melee",
        "roles":[
            "Initiator",
            "Jungler",
            "Escape",
            "Disabler"
        ]
    },
    {
        "id":56,
        "name":"Clinkz",
        "primary_attr":"agi",
        "attack_type":"Ranged",
        "roles":[
            "Carry",
            "Escape",
            "Pusher"
        ]
    },
    {
        "id":57,
        "name":"Omniknight",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Support",
            "Durable",
            "Nuker"
        ]
    },
    {
        "id":58,
        "name":"Enchantress",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Support",
            "Jungler",
            "Pusher",
            "Durable",
            "Disabler"
        ]
    },
    {
        "id":59,
        "name":"Huskar",
        "primary_attr":"str",
        "attack_type":"Ranged",
        "roles":[
            "Carry",
            "Durable",
            "Initiator"
        ]
    },
    {
        "id":60,
        "name":"Night Stalker",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Initiator",
            "Durable",
            "Disabler",
            "Nuker"
        ]
    },
    {
        "id":61,
        "name":"Broodmother",
        "primary_attr":"agi",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Pusher",
            "Escape",
            "Nuker"
        ]
    },
    {
        "id":62,
        "name":"Bounty Hunter",
        "primary_attr":"agi",
        "attack_type":"Melee",
        "roles":[
            "Escape",
            "Nuker"
        ]
    },
    {
        "id":63,
        "name":"Weaver",
        "primary_attr":"agi",
        "attack_type":"Ranged",
        "roles":[
            "Carry",
            "Escape"
        ]
    },
    {
        "id":64,
        "name":"Jakiro",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Support",
            "Nuker",
            "Pusher",
            "Disabler"
        ]
    },
    {
        "id":65,
        "name":"Batrider",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Initiator",
            "Jungler",
            "Disabler",
            "Escape"
        ]
    },
    {
        "id":66,
        "name":"Chen",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Support",
            "Jungler",
            "Pusher"
        ]
    },
    {
        "id":67,
        "name":"Spectre",
        "primary_attr":"agi",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Durable",
            "Escape"
        ]
    },
    {
        "id":68,
        "name":"Ancient Apparition",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Support",
            "Disabler",
            "Nuker"
        ]
    },
    {
        "id":69,
        "name":"Doom",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Disabler",
            "Initiator",
            "Durable",
            "Nuker"
        ]
    },
    {
        "id":70,
        "name":"Ursa",
        "primary_attr":"agi",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Jungler",
            "Durable",
            "Disabler"
        ]
    },
    {
        "id":71,
        "name":"Spirit Breaker",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Initiator",
            "Disabler",
            "Durable",
            "Escape"
        ]
    },
    {
        "id":72,
        "name":"Gyrocopter",
        "primary_attr":"agi",
        "attack_type":"Ranged",
        "roles":[
            "Carry",
            "Nuker",
            "Disabler"
        ]
    },
    {
        "id":73,
        "name":"Alchemist",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Support",
            "Durable",
            "Disabler",
            "Initiator",
            "Nuker"
        ]
    },
    {
        "id":74,
        "name":"Invoker",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Carry",
            "Nuker",
            "Disabler",
            "Escape",
            "Pusher"
        ]
    },
    {
        "id":75,
        "name":"Silencer",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Carry",
            "Support",
            "Disabler",
            "Initiator",
            "Nuker"
        ]
    },
    {
        "id":76,
        "name":"Outworld Devourer",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Carry",
            "Nuker",
            "Disabler"
        ]
    },
    {
        "id":77,
        "name":"Lycan",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Pusher",
            "Jungler",
            "Durable",
            "Escape"
        ]
    },
    {
        "id":78,
        "name":"Brewmaster",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Initiator",
            "Durable",
            "Disabler",
            "Nuker"
        ]
    },
    {
        "id":79,
        "name":"Shadow Demon",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Support",
            "Disabler",
            "Initiator",
            "Nuker"
        ]
    },
    {
        "id":80,
        "name":"Lone Druid",
        "primary_attr":"agi",
        "attack_type":"Ranged",
        "roles":[
            "Carry",
            "Pusher",
            "Jungler",
            "Durable"
        ]
    },
    {
        "id":81,
        "name":"Chaos Knight",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Disabler",
            "Durable",
            "Pusher",
            "Initiator"
        ]
    },
    {
        "id":82,
        "name":"Meepo",
        "primary_attr":"agi",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Escape",
            "Nuker",
            "Disabler",
            "Initiator",
            "Pusher"
        ]
    },
    {
        "id":83,
        "name":"Treant Protector",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Support",
            "Initiator",
            "Durable",
            "Disabler",
            "Escape"
        ]
    },
    {
        "id":84,
        "name":"Ogre Magi",
        "primary_attr":"int",
        "attack_type":"Melee",
        "roles":[
            "Support",
            "Nuker",
            "Disabler",
            "Durable",
            "Initiator"
        ]
    },
    {
        "id":85,
        "name":"Undying",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Support",
            "Durable",
            "Disabler",
            "Nuker"
        ]
    },
    {
        "id":86,
        "name":"Rubick",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Support",
            "Disabler",
            "Nuker"
        ]
    },
    {
        "id":87,
        "name":"Disruptor",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Support",
            "Disabler",
            "Nuker",
            "Initiator"
        ]
    },
    {
        "id":88,
        "name":"Nyx Assassin",
        "primary_attr":"agi",
        "attack_type":"Melee",
        "roles":[
            "Disabler",
            "Nuker",
            "Initiator",
            "Escape"
        ]
    },
    {
        "id":89,
        "name":"Naga Siren",
        "primary_attr":"agi",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Support",
            "Pusher",
            "Disabler",
            "Initiator",
            "Escape"
        ]
    },
    {
        "id":90,
        "name":"Keeper of the Light",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Support",
            "Nuker",
            "Disabler",
            "Jungler"
        ]
    },
    {
        "id":91,
        "name":"Io",
        "primary_attr":"str",
        "attack_type":"Ranged",
        "roles":[
            "Support",
            "Escape",
            "Nuker"
        ]
    },
    {
        "id":92,
        "name":"Visage",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Support",
            "Nuker",
            "Durable",
            "Disabler",
            "Pusher"
        ]
    },
    {
        "id":93,
        "name":"Slark",
        "primary_attr":"agi",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Escape",
            "Disabler",
            "Nuker"
        ]
    },
    {
        "id":94,
        "name":"Medusa",
        "primary_attr":"agi",
        "attack_type":"Ranged",
        "roles":[
            "Carry",
            "Disabler",
            "Durable"
        ]
    },
    {
        "id":95,
        "name":"Troll Warlord",
        "primary_attr":"agi",
        "attack_type":"Ranged",
        "roles":[
            "Carry",
            "Pusher",
            "Disabler",
            "Durable"
        ]
    },
    {
        "id":96,
        "name":"Centaur Warrunner",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Durable",
            "Initiator",
            "Disabler",
            "Nuker",
            "Escape"
        ]
    },
    {
        "id":97,
        "name":"Magnus",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Initiator",
            "Disabler",
            "Nuker",
            "Escape"
        ]
    },
    {
        "id":98,
        "name":"Timbersaw",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Nuker",
            "Durable",
            "Escape"
        ]
    },
    {
        "id":99,
        "name":"Bristleback",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Durable",
            "Initiator",
            "Nuker"
        ]
    },
    {
        "id":100,
        "name":"Tusk",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Initiator",
            "Disabler",
            "Nuker"
        ]
    },
    {
        "id":101,
        "name":"Skywrath Mage",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Support",
            "Nuker",
            "Disabler"
        ]
    },
    {
        "id":102,
        "name":"Abaddon",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Support",
            "Carry",
            "Durable"
        ]
    },
    {
        "id":103,
        "name":"Elder Titan",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Initiator",
            "Disabler",
            "Nuker",
            "Durable"
        ]
    },
    {
        "id":104,
        "name":"Legion Commander",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Disabler",
            "Initiator",
            "Durable",
            "Nuker"
        ]
    },
    {
        "id":105,
        "name":"Techies",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Nuker",
            "Disabler"
        ]
    },
    {
        "id":106,
        "name":"Ember Spirit",
        "primary_attr":"agi",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Escape",
            "Nuker",
            "Disabler",
            "Initiator"
        ]
    },
    {
        "id":107,
        "name":"Earth Spirit",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Nuker",
            "Escape",
            "Disabler",
            "Initiator",
            "Durable"
        ]
    },
    {
        "id":108,
        "name":"Underlord",
        "primary_attr":"str",
        "attack_type":"Melee",
        "roles":[
            "Support",
            "Nuker",
            "Disabler",
            "Durable",
            "Escape"
        ]
    },
    {
        "id":109,
        "name":"Terrorblade",
        "primary_attr":"agi",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Pusher",
            "Nuker"
        ]
    },
    {
        "id":110,
        "name":"Phoenix",
        "primary_attr":"str",
        "attack_type":"Ranged",
        "roles":[
            "Support",
            "Nuker",
            "Initiator",
            "Escape",
            "Disabler"
        ]
    },
    {
        "id":111,
        "name":"Oracle",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Support",
            "Nuker",
            "Disabler",
            "Escape"
        ]
    },
    {
        "id":112,
        "name":"Winter Wyvern",
        "primary_attr":"int",
        "attack_type":"Ranged",
        "roles":[
            "Support",
            "Disabler",
            "Nuker"
        ]
    },
    {
        "id":113,
        "name":"Arc Warden",
        "primary_attr":"agi",
        "attack_type":"Ranged",
        "roles":[
            "Carry",
            "Escape",
            "Nuker"
        ]
    },
    {
        "id":114,
        "name":"Monkey King",
        "primary_attr":"agi",
        "attack_type":"Melee",
        "roles":[
            "Carry",
            "Escape",
            "Disabler",
            "Initiator"
        ]
    }
];